; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=ProcSentinel
AppVersion=1.0
DefaultDirName={pf}\ProcSentinel
DefaultGroupName=ProcSentinel
OutputBaseFilename=ProcSentinelInstaller
SetupIconFile=icon.ico

